# Generated by Django 2.0.2 on 2018-08-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Estudiante')),
                ('codigo', models.CharField(max_length=12, verbose_name='Codigo')),
                ('carear', models.CharField(choices=[('informatica', 'Informática'), ('comercio', 'Comercio'), ('civil', 'Civil')], max_length=12, verbose_name='Carrera')),
                ('status', models.BooleanField(choices=[(True, 'Solvente'), (False, 'Moroso')], verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'estudiantes',
                'ordering': ['student_id'],
            },
        ),
    ]
