# Generated by Django 2.0.2 on 2018-08-02 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rfid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='codigo',
            new_name='code',
        ),
    ]
