# Generated by Django 2.0.2 on 2019-03-02 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_rfid', '0002_auto_20180801_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='code',
            new_name='card_code',
        ),
        migrations.AddField(
            model_name='student',
            name='cedula',
            field=models.CharField(default=django.utils.timezone.now, max_length=12, verbose_name='Cédula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='entry_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='solvency_status',
            field=models.BooleanField(choices=[(True, 'Solvente'), (False, 'Moroso')], default=True, verbose_name='Solvencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='carear',
            field=models.CharField(choices=[('informatica', 'Ingeniería Informática'), ('comercio', 'Comercio Internacional'), ('obras', 'Ingeniería en Mantenimiento de Obras')], max_length=12, verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.BooleanField(choices=[(True, 'Inscrito'), (False, 'No Inscrito')], verbose_name='Estatus de inscripción'),
        ),
    ]
