# Generated by Django 2.0.2 on 2019-03-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rfid', '0003_auto_20190301_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='carear',
            new_name='career',
        ),
    ]
