# Generated by Django 2.0.2 on 2019-03-02 03:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_rfid', '0004_auto_20190301_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='second_last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Segundo Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='second_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Segundo Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='card_code',
            field=models.CharField(max_length=12, verbose_name='Código del Carnet'),
        ),
        migrations.AlterField(
            model_name='student',
            name='career',
            field=models.CharField(choices=[('informatica', 'Ingeniería Informática'), ('comercio', 'Comercio Internacional'), ('obras', 'Ingeniería en Mantenimiento de Obras')], max_length=12, verbose_name='Carreras'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID del Estudiante'),
        ),
    ]
